version: '3'

services:
  orders-mysql-standalone-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=db_orders
      - MYSQL_USER=omgr
      - MYSQL_PASSWORD=omgr@123
    volumes:
      - /data/mysql1
  order-services-app-container:
    image: order-services-app:1
    ports:
      - 8081:8081
    environment:
      - MYSQL_HOST=orders-mysql-standalone-container
      - MYSQL_PORT=3306
      - WSERVER_PORT=8081
      - NOTIFICATIONS_HOST=192.168.99.112
      - NOTIFICATIONS_PORT=8082
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - orders-mysql-standalone-container
    volumes:
      - /data/order-services-app